### ISSUE TITLE
Issue with urn:xmpp:mam:2 support?

### ISSUE THREAD

**Issue by pkukkon** [igniterealtime/openfire-monitoring-plugin#121]
We're running Converse 6.0.0 (headless) against Openfire 4.5.3 + Monitoring Service 2.0.1 and there seems to be some sort of anomaly when querying urn:xmpp:mam:2. The stanza from Converse...

`<body rid="4084962494831216" xmlns="http://jabber.org/protocol/httpbind" sid="5nw3htpefo"><iq type="get" xmlns="jabber:client" id="3101cddf-b870-4282-babf-cd97d74d1409:sendIQ"><prefs xmlns="urn:xmpp:mam:2"/></iq></body>`

...is replied with...

`<body xmlns="http://jabber.org/protocol/httpbind" ack="4084962494831215"><iq xmlns="jabber:client" type="error" id="0128adfa-86e1-430c-891b-0b0a8543e933:sendIQ" to="user@domain/5nw3htpefo"><error code="501" type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq></body>`

...which seems a bit weird as shouldn't Monitoring Service support XEP-0313?

**Comment by guusdk** [comment]
Converse makes use of the 'prefs' feature. From a protocol perspective, this is optional. Openfire and the monitoring plugin do not support this, which is why you're getting that error.

I've raised a ticket with Converse to not _require_ this feature: https://github.com/conversejs/converse.js/issues/1676

Openfire does have another, unrelated iissue with MAM:2 and personal archives: it doesn't always include a unique and stable message IDs: https://github.com/igniterealtime/openfire-monitoring-plugin/issues/105

**Comment by pkukkon** [comment]
Many thanks for the clarification! We'll track this issue over there then. Converse UUIDs prefixed with 'id' also cause a ton of crashes in Openfire but that is apparently already fixed by the next release (https://github.com/conversejs/converse.js/issues/2035) so archive support between these two might soon go swimmingly.

**Comment by guusdk** [comment]
> Converse UUIDs prefixed with 'id' also cause a ton of crashes in Openfire

We've also addressed that in the next version for the Monitoring plugin: https://github.com/igniterealtime/openfire-monitoring-plugin/issues/101
